### ISSUE TITLE
Version check erroneously reporting update

### ISSUE THREAD

**Issue by elderpyre** [karjah/BetterBedrockPublic#2]
![image](https://user-images.githubusercontent.com/12993554/71636882-dfc8a900-2beb-11ea-8434-e07966c0ea88.png)

Minecraft: 1.12.2
Forge: 14.23.5.2847
BetterBedrock: 5.1.11 (5.1)
Latest BetterBedrock on CurseForge: BetterBedrock-1.12.2-5.1.11.jar

**Comment by karjah** [comment]
This has been fixed, but not released yet.
